---
last_check:
  etag: '"fake_etaag"'
  version: 1.8.6
  at: 1487940199
checked_completion: true
completion_version: 1.8.6
endpoints:
  https://api.travis-ci.com/:
    access_token: fake-travis-com-token
  https://api.travis-ci.org/:
    access_token: fake-travis-org-token
